#!/bin/sh

# Determine the directory that the script exists in.
# From: https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself/4774063
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Start the tool in a terminal window.
osascript -e "tell app \"Terminal\"
    do script \"cd '$SCRIPTPATH' && ./Uchu.Tool --directory ~/.uchu\"
end tell"